// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  symbol: [
    {
      type: 'autogenerated',
      dirName: '.'
    }
  ]
}

module.exports = sidebars
